# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-11-18 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
